version: "3.6"

services:
    db:
        image: mariadb:10.5
        container_name: so-db
        environment:
            - MYSQL_DATABASE=squareone
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 3366:3306
        volumes:
            - .:/var/www
            - db-data:/var/lib/mysql

    php:
        image: squareone/so-php
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        container_name: so-php
        depends_on:
            - db
        volumes:
            - .:/var/www:cached

    nginx:
        image: squareone/so-nginx
        build:
            context: ./docker/nginx
        container_name: so-nginx
        depends_on:
            - php
        volumes:
            - .:/var/www:cached
        ports:
            - 8880:80

    mail:
        image: dockage/mailcatcher:0.6.5
        container_name: so-mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

    rabbitmq:
        image: rabbitmq:3-management
        container_name: so-rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=3pBRVIu08orKbB7ddlEFeSZ2sQ4kpX8d
            - RABBITMQ_NODENAME=rabbit@rabbitmq
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - rabbitmq-so:/var/lib/rabbitmq:cached

    phpmyadmin:
        image: squareone/so-phpmyadmin
        build:
            context: ./docker/phpmyadmin
        container_name: so-phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=
            - PMA_MAXNAVIGATIONITEMS=1000
        ports:
            - 8881:80
        depends_on:
            - db

volumes:
    db-data: {}
    rabbitmq-so: {}
